name: actlearn
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - arpack=3.7.0=hdefa2d7_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=2.4.2=py39h06a4308_1
  - bottleneck=1.3.2=py39hdd57654_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.4.26=h06a4308_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2022.5.18.1=py39h06a4308_0
  - cffi=1.15.0=py39hd667e15_1
  - click=8.0.4=py39h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorcet=3.0.0=py39h06a4308_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask=2021.10.0=pyhd3eb1b0_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - datashader=0.13.0=pyhd3eb1b0_1
  - datashape=0.5.4=py39h06a4308_1
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2021.10.0=py39h06a4308_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.7=h27087fc_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=h8e229c2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2022.1.0=pyhd3eb1b0_0
  - g-ir-build-tools=1.72.0=py39h3707be2_0
  - g-ir-host-tools=1.72.0=h1def2ed_0
  - gdk-pixbuf=2.42.6=h8cc273a_5
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h7b6447c_0
  - glib=2.70.2=h780b84a_4
  - glib-tools=2.70.2=h780b84a_4
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h58526e2_0
  - gobject-introspection=1.72.0=py39habf54e5_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.50.0=h8e749b2_2
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - harfbuzz=4.0.1=h40b6f09_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.14.8=pyhd3eb1b0_0
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd3eb1b0_0
  - igraph=0.9.7=hf5496dd_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py39hef51801_0
  - ipython=8.1.1=py39hf3d152e_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py39hf3d152e_0
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=4.4.0=py39h06a4308_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py39hf3d152e_0
  - jupyterlab_pygments=0.1.2=py_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - leidenalg=0.8.9=py39h5a03fae_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgd=2.3.3=h695aa2c_0
  - libgfortran-ng=11.2.0=h69a702a_15
  - libgfortran5=11.2.0=h5c6108e_15
  - libgirepository=1.72.0=h26ff761_0
  - libglib=2.70.2=h174f98d_4
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_3
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=hbc83047_0
  - librsvg=2.52.5=h0a9e6e8_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtiff=4.2.0=h85742a9_0
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=13.0.1=he0ac6c6_1
  - locket=0.2.1=py39h06a4308_2
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=py39h06a4308_0
  - markupsafe=2.0.1=py39h27cfd23_0
  - matplotlib-base=3.5.1=py39ha18d171_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - metis=5.1.0=h58526e2_1006
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mpfr=4.1.0=h9202a9a_1
  - msgpack-python=1.0.2=py39hff7bd54_1
  - multipledispatch=0.6.0=py39h06a4308_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.4.4=py39h06a4308_0
  - nbformat=5.3.0=py39h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - notebook=6.4.11=py39h06a4308_0
  - numexpr=2.8.1=py39h6abb31d_0
  - openssl=3.0.3=h166bdaf_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py39h295c915_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.13.1=py_0
  - pango=1.50.6=hbd2fdc8_0
  - param=1.12.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.27=pyha770c72_0
  - psutil=5.8.0=py39h27cfd23_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.4.6=py39h06a4308_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pygraphviz=1.9=py39ha206bd0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.10=hc74c709_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-igraph=0.9.9=py39hfef886c_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd3eb1b0_0
  - pyviz_comms=2.2.0=py_0
  - pyyaml=6.0=py39h7f8727e_1
  - pyzmq=19.0.2=py39hb69f2a1_2
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.0=hc218d9a_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - suitesparse=5.10.1=h9e50725_1
  - tbb=2021.5.0=h924138e_1
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.13.1=py39h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - texttable=1.6.4=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py39h3811e60_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xarray=0.20.1=pyhd3eb1b0_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.8.0=py39h06a4308_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.4.9=haebb681_0
  - pip:
    - anndata==0.8.0
    - appdirs==1.4.4
    - beautifulsoup4==4.10.0
    - bioservices==1.8.4
    - cattrs==1.10.0
    - causaldag==0.1a163
    - charset-normalizer==2.0.12
    - colorlog==6.6.0
    - conditional-independence==0.1a5
    - contrastive==1.1.0
    - dataclasses==0.6
    - easydev==0.12.0
    - fonttools==4.30.0
    - frozendict==2.3.0
    - future==0.18.2
    - gevent==21.12.0
    - graphical-model-learning==0.1a7
    - graphical-models==0.1a13
    - graphviz==0.20.1
    - greenlet==1.1.2
    - grequests==0.6.0
    - gseapy==0.10.8
    - h5py==3.6.0
    - ipdb==0.13.9
    - kiwisolver==1.3.2
    - louvain==0.7.1
    - lxml==4.8.0
    - matplotlib-venn==0.11.6
    - natsort==8.1.0
    - numba==0.55.2
    - numpy==1.22.3
    - patsy==0.5.2
    - pillow==9.0.1
    - progressbar2==4.0.0
    - pygam==0.8.0
    - pynndescent==0.5.6
    - python-utils==3.1.0
    - requests-cache==0.9.3
    - scanpy==1.9.1
    - scikit-learn==1.0.2
    - scikit-network==0.25.0
    - scipy==1.8.0
    - seaborn==0.11.2
    - session-info==1.0.0
    - sklearn==0.0
    - statsmodels==0.13.2
    - stdlib-list==0.8.0
    - suds-community==1.0.0
    - toml==0.10.2
    - tqdm==4.63.0
    - typing==3.7.4.3
    - umap-learn==0.5.2
    - url-normalize==1.4.3
    - urllib3==1.26.8
    - wrapt==1.14.0
    - xmltodict==0.12.0
    - zope-event==4.5.0
    - zope-interface==5.4.0
prefix: /home/vzhang/miniconda3/envs/actlearn
